"""empty message

Revision ID: 079b33409ec1
Revises: 1a13991a5b75
Create Date: 2021-12-31 17:27:14.208813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079b33409ec1'
down_revision = '1a13991a5b75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_actors',
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_actors')
    op.drop_table('contacts')
    # ### end Alembic commands ###
